#%%
# minimal peptide→protein check (no external deps)
protein = "MAEAELHKERLQAIAEKRKRQTEIEGKRRQLDEQVLLLQHSKSKVLREKWLLQGVPAGTAEEEEARRRQSEEDEFKVKQLEDNIQRLEQEIQALESEESQISAKEQIILEKLKETEKSFKDLQKSFSTADGASGWSTVLLQGDELTADPIGTNADMAIQKPPQLSEDANQLRSKQDNCGDSRLEPAASSLSPDHKNMEIGVSVAECKSVPGVTSTPHSKDHSSPFYSPSHNGLLADHHESLDNDVAREIQYLDEVLEANCCDSSVDGTYNGISSPEPGAAILVSSLGSPAHSVTEAEPTEKASGRQVPPHIELSRSPSDRMAEGERANGHSTDQPQDLLGNSLQAPASPSSSTSSHCSSRDGEFTLTTLKKEAKFELRAFHEDKKPSKLFEEDEREKEQFCVRKVRPSEEMIELEKERRELIRSQAVKKNPGIAAKWWNPPQEKTIEEQLDEEHLESHRKYKERKEKRAQQEQLQLQQQQQQQLQQQQLQQQQLQQQQLQQQLQQQQLSTSQPCTAPAAHKHLDGIEHTKEDVVTEQIDFSAARKQFQLMENSRQTLAKGQSTPRLFSIKPYYKPLGSIHSDKPPTILRPATVGGTLEDGGTQAAKEQKAPCVSESQSAGAGPANAATQGKEGPYSEPSKRGPLSKLWAEDGEFTSARAVLTVVKDEDHGILDQFSRSVNVSLTQEELDSGLDELSVRSQDTTVLETLSNDFSMDNISDSGASNETPSALQENSLADFSLPQTPQTDNPSEGREGVSKSFSDHGFYSPSSTLGDSPSVDDPLEYQAGLLVQNAIQQAIAEQVDKAEAHTSKEGSEQQEPEATVEEAGSQTPGSEKPQGMFAPPQVSSPVQEKRDILPKNLPAEDRALREKGPSQPPTAAQPSGPVNMEETRPEGGYFSKYSEAAELRSTASLLATQESDVMVGPFKLRSRKQRTLSMIEEEIRAAQEREEELKRQRQVRQSTPSPRAKNAPSLPSRTTCYKTAPGKIEKVKPPPSPTTEGPSLQPDLAPEEAAGTQRPKNLMQTLMEDYETHKSKRRERMDDSSYTSKLLSCKVTSEVLEATRVNRRKSALALRWEAGIYANQEEEDNE"
peptides = ["DEDDEKSLREKTV", "SDTTEPSSPEGKE", "DTTEPSSPEGKEE"]

def find_exact(p, prot):
    idx = prot.find(p)
    return (idx+1, idx+len(p)) if idx >= 0 else None

def best_approx(p, prot):
    L = len(p)
    best = {"start":None,"end":None,"identity":0.0,"match":None}
    for i in range(0, len(prot)-L+1):
        w = prot[i:i+L]
        matches = sum(1 for a,b in zip(w, p) if a==b)
        ident = matches / L
        if ident > best["identity"]:
            best = {"start": i+1, "end": i+L, "identity": ident, "match": w}
    return best

for pep in peptides:
    pep_u = pep.upper()
    ex = find_exact(pep_u, protein)
    if ex:
        print(f"{pep}: exact at {ex[0]}-{ex[1]}")
    else:
        a = best_approx(pep_u, protein)
        print(f"{pep}: NO exact match. Best approx {a['start']}-{a['end']} "
              f"match='{a['match']}' identity={a['identity']:.2f}")

# %%
